Added root user check. Which you can toggle off.
User by default are not allowed to run the script as a root user.

However that can explicitaly be disabled by using the --unsafe option.

However note that variable parsing happens before the root check.
Otherwise we couldn't depend on the --unsafe flag as that needs to be
parsed.

Thus future developers should be aware that any logic in the command
parser can be affected by the privileges of a root user

diff --git a/wm-launch b/wm-launch
--- a/wm-launch
+++ b/wm-launch
@@ -17,6 +17,9 @@ ROOT_PATH="${ROOT_PATH:-/usr/bin}"
 # eg gdb -> gdb "$EXEC" instead of "$EXEC"
 PARENT_COMMAND=""
 
+# disable root execution by default
+UNSAFE=""
+
 function log {
     echo -e "$@"
 }
@@ -43,15 +46,24 @@ function is-installed {
     fi
 }
 
+function check-non-root {
+    if [[ "$(id -u)" == "0" && "$UNSAFE" = "" ]]; then
+        log "$LOG_ERROR" "Don't run this script as root. We will ask for privileges when needed."
+        log "$LOG_ERROR" "If you still want to run this program as root simply add the --unsafe option"
+        exit 1
+    fi
+}
+
 function help {
     name="wm-launch"
-    echo -e "$name [-hrdeSRsgc] -di"
+    echo -e "$name [-hrdeSRsgc] -di --unsafe"
     echo -e "\nPOSITIONAL ARGUMENTS:"
     echo -e "$name -h | --help\t\t\t\tPrint this help message."
     echo -e "$name -r | --resolution <XxY>\t\tSet the resolution of the awesome window in Xaxis x Yaxis eg 1920x1080 (default 800x600"
     echo -e "$name -d | --display <number>\t\tSet the display on which to show the window (by default :1)"
     echo -e "$name -e | --exec command\t\t\tCommand to execute in the environment eg awesome"
     echo -e "$name -s | --stop \t\t\t\tStop all instances"
+    echo -e "$name --unsafe \t\t\t\t\tAllow running this utility as root"
     echo -e "\nPROFILING COMMANDS:"
     echo -e "$name -S | --sample \t\t\tSample the process using Oprofile"
     echo -e "$name -R | --report \t\t\tGet the report of the Oprofile tool"
@@ -128,6 +140,9 @@ function set-variables {
                 help
                 exit 0
         fi
+        if [[ "$1" == "--unsafe" ]]; then
+            UNSAFE="1"
+        fi
         shift
     done
 }
@@ -167,7 +182,9 @@ function launch {
 
 }
 
-is-installed
 
+is-installed
 set-variables "$@"
+check-non-root
+
 launch
