Added gdb to the script for easier debugging

diff --git a/wm-launch b/wm-launch
--- a/wm-launch
+++ b/wm-launch
@@ -13,15 +13,30 @@ RESOLUTION="${RES:-800x600}"
 EXEC="${EXEC:-awesome}"
 ROOT_PATH="${ROOT_PATH:-/usr/bin}"
 
+# by default we don't need to call a parent command
+# eg gdb -> gdb "$EXEC" instead of "$EXEC"
+PARENT_COMMAND=""
+
 function log {
     echo -e "$@"
 }
 
-function is-installed {
-    if [[ ! "$(command -v awesome)" ]]; then
-            log "$LOG_ERROR" "Awesome is not installed. Aborting..."
-            exit 1
+# Check that all inputs are valid.
+# Currently checks to see if the command that should be executed exists
+# Otherwise abort
+function validate {
+    # EXEC can be a command together with specific options
+    # This line retreives the command (the first parameter)
+    COMMAND="$(echo "$EXEC" | cut -d" " -f1 )"
+    if [[ ! "$(command -v $COMMAND)" ]]; then
+        log "$LOG_ERROR" "Command $COMMAND is not installed."
+        exit 1
     fi
+}
+
+function is-installed {
+    validate
+
     if [[ ! "$(command -v Xephyr)" ]]; then
             log "$LOG_ERROR" "Xephyr is not installed. Aborting..."
             exit 1
@@ -30,7 +45,7 @@ function is-installed {
 
 function help {
     name="wm-launch"
-    echo -e "$name [-hrdeSRsc] -di"
+    echo -e "$name [-hrdeSRsgc] -di"
     echo -e "\nPOSITIONAL ARGUMENTS:"
     echo -e "$name -h | --help\t\t\t\tPrint this help message."
     echo -e "$name -r | --resolution <XxY>\t\tSet the resolution of the awesome window in Xaxis x Yaxis eg 1920x1080 (default 800x600"
@@ -41,6 +56,8 @@ function help {
     echo -e "$name -S | --sample \t\t\tSample the process using Oprofile"
     echo -e "$name -R | --report \t\t\tGet the report of the Oprofile tool"
     echo -e "$name -c | --cleanup \t\t\tRemove the generated files and directories"
+    echo -e "\nDEBUGGING COMMANDS:"
+    echo -e "$name -g | --gdb \t\t\t\tOpen your tool in gdb"
     echo -e "\nSETUP COMMANDS:"
     echo -e "$name -i | --init \t\t\t\tMake a symbolic like to your PATH. Making this script accessible from everywhere"
     echo -e "$name -di | --deinit \t\t\tRemove the symbolic link that has been created"
@@ -65,7 +82,10 @@ function set-variables {
             shift
         fi
         if [[ "$1" == "-S" || "$1" == "--sample" ]]; then
-                SAMPLE="1"
+                PARENT_COMMAND="operf"
+        fi
+        if [[ "$1" == "-g" || "$1" == "--gdb" ]]; then
+                PARENT_COMMAND="gdb"
         fi
         if [[ "$1" == "-R" || "$1" == "--report" ]]; then
                 opreport -cl --demangle=smart `which awesome`
@@ -111,15 +131,18 @@ function set-variables {
     done
 }
 
-# Check that all inputs are valid.
-# Currently checks to see if the command that should be executed exists
-# Otherwise abort
-function validate {
-    # EXEC can be a command together with specific options
-    # This line retreives the command (the first parameter)
-    COMMAND="$(echo "$EXEC" | cut -d" " -f1 )"
-    if [[ ! "$(command -v $COMMAND)" ]]; then
-        log "$LOG_ERROR" "Command $COMMAND is not installed."
+function checkOperf {
+    if [[ ! "$(command -v operf)" ]]; then
+        log "$LOG_ERROR" "operf is required to profile the window manager, operf is part of OProfile"
+        abort
+        exit 1
+    fi
+}
+
+function checkGDB {
+    if [[ ! "$(command -v gdb)" ]]; then
+        log "$LOG_ERROR" "gdb is required to debug the window manager, Install gdb for this to work"
+        abort
         exit 1
     fi
 }
@@ -127,26 +150,24 @@ function validate {
 function launch {
     Xephyr -br -ac -noreset -screen "$RESOLUTION" "$AWESOME_DISPLAY"  &
     sleep 1
-    if [[ "$SAMPLE" == "1" ]]; then
-        if [[ ! "$(command -v operf)" ]]; then
-            log "$LOG_ERROR" "operf is required to debug the window manager, operf is part of OProfile"
-            abort
-            exit 1
-        fi
+    if [[ "$PARENT_COMMAND" == "operf" ]]; then
+        checkOperf
         log "$LOG_WARN" "Notifying kernel of profile sampling mode (requires elevated privileges)" 
-        log "$LOG_WARN" "Executing $EXEC"
+        log "$LOG_WARN" "Executing $EXEC with $PARENT_COMMAND"
         sudo sysctl kernel.perf_event_paranoid=1
-        # Not quoted because the variable can hold the options as well
-        DISPLAY="$AWESOME_DISPLAY" operf $EXEC
+    elif [[ "$PARENT_COMMAND" == "gdb" ]]; then
+        checkGDB
+        log "$LOG_WARN" "Executing $EXEC under gdb"
     else
         log "$LOG_WARN" "Executing $EXEC"
-        # Not quoted because the variable can hold the options as well
-        DISPLAY="$AWESOME_DISPLAY" $EXEC
     fi
+    
+    # Not quoted because the variable can hold the options as well
+    DISPLAY="$AWESOME_DISPLAY" "$PARENT_COMMAND" $EXEC
+
 }
 
 is-installed
 
 set-variables "$@"
-validate
 launch
